spring: 
   jackson:
      serialization:
         INDENT_OUTPUT: true
#   datasource:
#      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
#      username: postgres
#      password: admin
#      cachePrepStmts: true
#      prepStmtCacheSize: 250
#      prepStmtCacheSqlLimit: 2048
#      useServerPrepStmts: true 
#      hikari:
#          connection-timeout: 20000
#          minimum-idle: 10
#          maximum-pool-size: 10
#          idle-timeout: 10000
#          max-lifetime: 1000
#          auto-commit: true 
#   jpa:
#      database: default
##      show-sql: true
#      properties:
#         hibernate:
#            format_sql: true
#      hibernate: 
##         ddl-auto: create-drop
#         ddl-auto: update
server:
   port: 8080
   
